# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 570303b1902b24de6bc986fbebffeca342706845efa90cd9cadc4297b7d34f98dd66a4657d484f3d729ff15f19b064e475d2ddcfe6b7df0aba2723690b21a93c

test:
  secret_key_base: ae5f0ea250946ac0d131c55a86b6db5db5251bedd50d00806425b7f805f9f8899e4a4536218ae512a7c80f2caab1653643f57bea1a0fb00bc2a0c0237d648fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
